name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Read .node-version
        id: node-version
        run: echo "node-version=$(cat .node-version)" >> $GITHUB_OUTPUT
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: ${{ steps.node-version.outputs.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
